/*
    Warning - this file was autogenerated by genparse
    DO NOT EDIT - any changes will be lost
*/

#ifndef HFP_PARSE_H
#define HFP_PARSE_H

#include <message_.h>

#ifdef __XAP__
#include <source.h>
#endif

const u8 *parseData(const u8 *s, const u8 *e, Task task);
void handleUnrecognised(const u8 *data, u16 length, Task task);

#ifdef __XAP__
u16 parseSource(Source rfcDataIncoming, Task task);
#endif

struct sequence
{
  const u8 *data;
  u16 length;
};

struct value_hfpCsrFeaturesHandleModifyIndicatorsInd_p
{
  u16 ind;
  u16 val;
};
struct region_hfpCsrFeaturesHandleModifyIndicatorsInd_p
{
  u16 count;
  const u8 *s;
  const u8 *e;
  u16 next;
  const u8 *next_s;
};
struct value_hfpCsrFeaturesHandleModifyIndicatorsInd_p get_hfpCsrFeaturesHandleModifyIndicatorsInd_p(const struct region_hfpCsrFeaturesHandleModifyIndicatorsInd_p*, u16);

struct value_hfpHandleCallHoldInfoRange_p
{
  u16 lower;
  u16 upper;
};
struct region_hfpHandleCallHoldInfoRange_p
{
  u16 count;
  const u8 *s;
  const u8 *e;
  u16 next;
  const u8 *next_s;
};
struct value_hfpHandleCallHoldInfoRange_p get_hfpHandleCallHoldInfoRange_p(const struct region_hfpHandleCallHoldInfoRange_p*, u16);

struct value_hfpHandleCallHoldInfo_p
{
  struct sequence n;
};
struct region_hfpHandleCallHoldInfo_p
{
  u16 count;
  const u8 *s;
  const u8 *e;
  u16 next;
  const u8 *next_s;
};
struct value_hfpHandleCallHoldInfo_p get_hfpHandleCallHoldInfo_p(const struct region_hfpHandleCallHoldInfo_p*, u16);

struct value_hfpHandleIndicatorStatus_d
{
  u16 n;
};
struct region_hfpHandleIndicatorStatus_d
{
  u16 count;
  const u8 *s;
  const u8 *e;
  u16 next;
  const u8 *next_s;
};
struct value_hfpHandleIndicatorStatus_d get_hfpHandleIndicatorStatus_d(const struct region_hfpHandleIndicatorStatus_d*, u16);

struct hfpHandleCurrentCallsWithNumber
{
  u16 dir;
  u16 idx;
  struct sequence ignore;
  u16 mode;
  u16 mprty;
  struct sequence number;
  u16 status;
  u16 type;
};
struct hfpHandleCurrentCalls
{
  u16 dir;
  u16 idx;
  struct sequence ignore;
  u16 mode;
  u16 mprty;
  u16 status;
};
struct hfpHandleResponseWbsCodec
{
  u16 codec;
};
struct hfpCsrFeaturesHandleModifyIndicatorsInd
{
  struct region_hfpCsrFeaturesHandleModifyIndicatorsInd_p p;
};
struct hfpHandleMicrophoneGain
{
  u16 gain;
};
struct hfpHandleSpeakerGain
{
  u16 gain;
};
struct hfpHandleDataResponse
{
  struct sequence num;
};
struct hfpHandleDataResponseExtended
{
  struct sequence ignore;
  struct sequence num;
};
struct hfpHandleSupportedFeaturesInd
{
  u16 supportedfeat;
};
struct hfpHandleInBandRingTone
{
  u16 enable;
};
struct hfpHandleResponseHold
{
  u16 state;
};
struct hfpHandleVoiceRecognitionStatus
{
  u16 enable;
};
struct hfpHandleCallWaitingNotificationWithName
{
  u16 class;
  struct sequence ignore;
  struct sequence name;
  struct sequence num;
  u16 type;
};
struct hfpHandleCallWaitingNotification
{
  struct sequence ignore;
  struct sequence num;
  u16 type;
};
struct hfpHandleCallWaitingNotificationIllegal
{
  struct sequence ignore;
  struct sequence num;
};
struct hfpHandleCallHoldInfoRange
{
  struct region_hfpHandleCallHoldInfoRange_p p;
};
struct hfpHandleCallHoldInfo
{
  struct region_hfpHandleCallHoldInfo_p p;
};
struct hfpHandleIndicatorStatusUpdate
{
  u16 index;
  u16 value;
};
struct hfpHandleIndicatorStatus
{
  struct region_hfpHandleIndicatorStatus_d d;
};
struct hfpHandleIndicatorList
{
  struct sequence str;
};
struct hfpHandleCallerIdWithName
{
  struct sequence ignore;
  struct sequence name;
  struct sequence num;
  struct sequence saddr;
  struct sequence satype;
  u16 type;
};
struct hfpHandleCallerId
{
  struct sequence ignore;
  struct sequence num;
  u16 type;
};
struct hfpHandleCallerIdIllegal
{
  struct sequence ignore;
  struct sequence num;
};
struct hfpHandleSubscriberNumber
{
  struct sequence alpha;
  struct sequence number;
  u16 service;
  struct sequence speed;
  u16 type;
};
struct hfpHandleNetworkOperatorModeName
{
  u16 format;
  u16 mode;
  struct sequence operator;
};
struct hfpHandleNetworkOperatorMode
{
  struct sequence ignore;
  u16 mode;
};
struct hfpHandleNull
{
  struct sequence str;
};
struct hfpCsrFeaturesHandleBandwidthCodecRes
{
  u16 battlevel;
  u16 callername;
  u16 codecbandwidths;
  u16 codecs;
  struct sequence ignore;
  u16 pwrsource;
  u16 rawtext;
  u16 sms;
};
struct hfpCsrFeaturesHandleCodecRes
{
  u16 battlevel;
  u16 callername;
  u16 codecs;
  struct sequence ignore;
  u16 pwrsource;
  u16 rawtext;
  u16 sms;
};
struct hfpCsrFeaturesHandleNormalRes
{
  u16 battlevel;
  u16 callername;
  struct sequence ignore;
  u16 pwrsource;
  u16 rawtext;
  u16 sms;
};
struct hfpCsrFeaturesHandleSmsInd
{
  struct sequence ignore;
  struct sequence senderName;
  struct sequence senderNum;
  u16 smsIndex;
};
struct hfpCsrFeaturesHandleTextInd
{
  struct sequence text;
};
struct hfpHandleExtendedError
{
  u16 err;
};
struct hfpCsrFeaturesHandleGetSmsRes
{
  struct sequence sms;
};
void hfpHandleOk(Task );
void hfpHandleError(Task );
void hfpHandleRing(Task );
void hfpHandleInBandRingToneDisable(Task );
void hfpHandleInBandRingToneEnable(Task );
void hfpHandleCallHoldInfoCommon(Task );
void hfpHandleCurrentCallsWithNumber(Task , const struct hfpHandleCurrentCallsWithNumber *);
void hfpHandleCurrentCalls(Task , const struct hfpHandleCurrentCalls *);
void hfpHandleResponseWbsCodec(Task , const struct hfpHandleResponseWbsCodec *);
void hfpCsrFeaturesHandleModifyIndicatorsInd(Task , const struct hfpCsrFeaturesHandleModifyIndicatorsInd *);
void hfpCsrFeaturesHandleDisableIndicatorsInd(Task );
void hfpHandleMicrophoneGain(Task , const struct hfpHandleMicrophoneGain *);
void hfpHandleSpeakerGain(Task , const struct hfpHandleSpeakerGain *);
void hfpHandleDataResponse(Task , const struct hfpHandleDataResponse *);
void hfpHandleDataResponseExtended(Task , const struct hfpHandleDataResponseExtended *);
void hfpHandleSupportedFeaturesInd(Task , const struct hfpHandleSupportedFeaturesInd *);
void hfpHandleInBandRingTone(Task , const struct hfpHandleInBandRingTone *);
void hfpHandleResponseHold(Task , const struct hfpHandleResponseHold *);
void hfpHandleVoiceRecognitionStatus(Task , const struct hfpHandleVoiceRecognitionStatus *);
void hfpHandleCallWaitingNotificationWithName(Task , const struct hfpHandleCallWaitingNotificationWithName *);
void hfpHandleCallWaitingNotification(Task , const struct hfpHandleCallWaitingNotification *);
void hfpHandleCallWaitingNotificationIllegal(Task , const struct hfpHandleCallWaitingNotificationIllegal *);
void hfpHandleCallHoldInfoRange(Task , const struct hfpHandleCallHoldInfoRange *);
void hfpHandleCallHoldInfo(Task , const struct hfpHandleCallHoldInfo *);
void hfpHandleIndicatorStatusUpdate(Task , const struct hfpHandleIndicatorStatusUpdate *);
void hfpHandleIndicatorStatus(Task , const struct hfpHandleIndicatorStatus *);
void hfpHandleIndicatorList(Task , const struct hfpHandleIndicatorList *);
void hfpHandleCallerIdWithName(Task , const struct hfpHandleCallerIdWithName *);
void hfpHandleCallerId(Task , const struct hfpHandleCallerId *);
void hfpHandleCallerIdIllegal(Task , const struct hfpHandleCallerIdIllegal *);
void hfpHandleSubscriberNumber(Task , const struct hfpHandleSubscriberNumber *);
void hfpHandleNetworkOperatorModeName(Task , const struct hfpHandleNetworkOperatorModeName *);
void hfpHandleNetworkOperatorMode(Task , const struct hfpHandleNetworkOperatorMode *);
void hfpHandleNull(Task , const struct hfpHandleNull *);
void hfpCsrFeaturesHandleBandwidthCodecRes(Task , const struct hfpCsrFeaturesHandleBandwidthCodecRes *);
void hfpCsrFeaturesHandleCodecRes(Task , const struct hfpCsrFeaturesHandleCodecRes *);
void hfpCsrFeaturesHandleNormalRes(Task , const struct hfpCsrFeaturesHandleNormalRes *);
void hfpCsrFeaturesHandleSmsInd(Task , const struct hfpCsrFeaturesHandleSmsInd *);
void hfpCsrFeaturesHandleTextInd(Task , const struct hfpCsrFeaturesHandleTextInd *);
void hfpHandleExtendedError(Task , const struct hfpHandleExtendedError *);
void hfpCsrFeaturesHandleBatteryLevelRequestInd(Task );
void hfpCsrFeaturesHandleGetSmsRes(Task , const struct hfpCsrFeaturesHandleGetSmsRes *);
void hfpHandleNoCarrierInd(Task );

#endif
