#include <csrtypes.h>
void AudioGetLatency(){}
void BootGetMode(){}
void BootSetMode(){}
void ChargerConfigure(){}
void ChargerDebounce(){}
void ConnectionL2capConnectRequest(){}
void ConnectionL2capConnectResponse(){}
void ConnectionL2capDisconnectRequest(){}
void ConnectionL2capDisconnectResponse(){}
void ConnectionL2capRegisterRequest(){}
void FileFind(){}
void I2cTransfer(){}
void KalimbaLoad(){}
void KalimbaPowerOff(){}
void KalimbaSendLongMessage(){}
void KalimbaSendMessage(){}
void LedConfigure(){}
void LoaderModeEnter(){}
void MessageBlueStackTask(){}
void MessageCancelAll(){}
void MessageCancelFirst(){}
void MessageChargerTask(){}
void MessageKalimbaTask(){}
void MessageLoop(){}
void MessagePioTask(){}
void MessageSend(){}
void MessageSendConditionally(){}
void MessageSendConditionallyOnTask(){}
void MessageSendLater(){}
void MessageSinkGetTask(){}
void MessageSinkTask(){}
void MessageSystemTask(){}
void MicbiasConfigure(){}
void PanicUnlessMalloc(){}
void PioDebounce32(){}
void PioGet32(){}
void PioSet32(){}
void PioSetDir32(){}
void PioSetFunction(){}
void PioSetMapPins32(){}
void PsFlood(){}
void PsFreeCount(){}
void PsFullRetrieve(){}
void PsRetrieve(){}
void PsStore(){}
void PsuConfigure(){}
void PsuGetVregEn(){}
void RegionWriteUnsigned(){}
void SinkClaim(){}
void SinkClose(){}
void SinkConfigure(){}
void SinkFlush(){}
void SinkGetBdAddr(){}
void SinkGetL2capCid(){}
void SinkGetRfcommConnId(){}
void SinkGetScoHandle(){}
void SinkIsValid(){}
void SinkMap(){}
void SinkSlack(){}
void SinkSynchronise(){}
void SourceBoundary(){}
void SourceClose(){}
void SourceConfigure(){}
void SourceDrop(){}
void SourceIsValid(){}
void SourceMap(){}
void SourceSize(){}
void SourceSynchronise(){}
void StreamAudioSink(){}
void StreamAudioSource(){}
void StreamConfigure(){}
void StreamConnect(){}
void StreamConnectAndDispose(){}
void StreamConnectDispose(){}
void StreamDisconnect(){}
void StreamFileSource(){}
void StreamKalimbaSink(){}
void StreamL2capSink(){}
void StreamRfcommSink(){}
void StreamRingtoneSource(){}
void StreamScoSink(){}
void StreamSinkFromSource(){}
void StreamSinksFromBdAddr(){}
void StreamSourceFromSink(){}
void TestTxStart(){}
void TransformAdpcmDecode(){}
void TransformStart(){}
void UtilCompare(){}
void UtilFind(){}
void UtilGetNumber(){}
void UtilHash(){}
void UtilRandom(){}
void VmGetHandleFromPointer(){}
void VmGetPointerFromHandle(){}
void VmGetPowerSource(){}
void VmGetResetSource(){}
void VmSendDmPrim(){}
void VmSendL2capPrim(){}
void VmSendRfcommPrim(){}
void VmSendSdpPrim(){}
void csr_cvsd_no_dsp_plugin(){}
void csr_sbc_decoder_plugin(){}
void sbc_caps_sink(){}
void VmGetAvailableAllocations(){}
void StreamHostSink() {}
